/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.reto4.view;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.reto4.controller.ControllerRequerimientos;
import utp.misiontic2022.c2.reto4.model.vo.Requerimiento_1;
import utp.misiontic2022.c2.reto4.model.vo.Requerimiento_2;
import utp.misiontic2022.c2.reto4.model.vo.Requerimiento_3;

/**
 *
 * @author Adrian
 */
public class FormRequerimientos extends javax.swing.JFrame {

    /**
     * Creates new form FormRequerimientos
     */
    public FormRequerimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPestanas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        RbtnReq1 = new javax.swing.JRadioButton();
        RbtnReq2 = new javax.swing.JRadioButton();
        RbtnReq3 = new javax.swing.JRadioButton();
        BtnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        DateIni = new com.toedter.calendar.JDateChooser();
        DateFin = new com.toedter.calendar.JDateChooser();
        RBtnFiltro = new javax.swing.JRadioButton();
        campoCiudad = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        labelDateIni = new javax.swing.JLabel();
        labelDateFin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numReg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UTP MISIONTIC 2021 CICLO 2");

        PanelPestanas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelPestanasFocusGained(evt);
            }
        });

        RbtnReq1.setText("Requerimiento 1");
        RbtnReq1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RbtnReq1StateChanged(evt);
            }
        });

        RbtnReq2.setText("Requerimiento 2");
        RbtnReq2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RbtnReq2StateChanged(evt);
            }
        });
        RbtnReq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnReq2ActionPerformed(evt);
            }
        });

        RbtnReq3.setText("Requerimiento 3");
        RbtnReq3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RbtnReq3StateChanged(evt);
            }
        });
        RbtnReq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnReq3ActionPerformed(evt);
            }
        });

        BtnConsulta.setText("Consultar");
        BtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaActionPerformed(evt);
            }
        });

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        DateIni.setEnabled(false);

        DateFin.setEnabled(false);

        RBtnFiltro.setText("Filtro Req 2");
        RBtnFiltro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RBtnFiltroStateChanged(evt);
            }
        });
        RBtnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnFiltroActionPerformed(evt);
            }
        });

        campoCiudad.setEnabled(false);

        labelCiudad.setForeground(new java.awt.Color(153, 153, 153));
        labelCiudad.setText("Ciudad");
        labelCiudad.setOpaque(true);

        labelDateIni.setForeground(new java.awt.Color(153, 153, 153));
        labelDateIni.setText("Fecha Inicial");
        labelDateIni.setOpaque(true);

        labelDateFin.setForeground(new java.awt.Color(153, 153, 153));
        labelDateFin.setText("Fecha Final");
        labelDateFin.setOpaque(true);

        jLabel2.setText("No. registros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(numReg))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RbtnReq1)
                                .addComponent(RBtnFiltro)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(RbtnReq2)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RbtnReq3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(BtnConsulta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelDateFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDateIni, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateFin, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(DateIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RBtnFiltro)
                        .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCiudad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDateIni)
                            .addComponent(DateIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDateFin))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnReq1)
                    .addComponent(RbtnReq2)
                    .addComponent(RbtnReq3)
                    .addComponent(BtnConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        PanelPestanas.addTab("Requerimientos", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("RETO 5");
        jLabel1.setName("titulo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPestanas)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelPestanasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelPestanasFocusGained
        // TODO add your handling code here:
        /*if (PanelPestanas.getSelectedIndex()== 1){
            new FormReqBusqueda().setVisible(true);
        }*/
    }//GEN-LAST:event_PanelPestanasFocusGained

    private void RBtnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnFiltroActionPerformed

    private void BtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaActionPerformed
        // TODO add your handling code here:
        ControllerRequerimientos controlador = new ControllerRequerimientos();
    
        Integer limit = null;
        
        boolean esNulo = true;
                
        if(!numReg.getText().equals("")){ //Escribió algo en la celda.
            esNulo = false;
        }        
        
        try{
            limit = Integer.parseInt(numReg.getText());

        }catch(NumberFormatException e){
            if(!esNulo){
                JOptionPane.showMessageDialog(this, "El campo No. Registros debe ser un entero, fue ignorado");
            }
            numReg.setText("");
        }

        if (RbtnReq1.isSelected()){
            String[] columnNombre = {"Fecha Compra", "Cod. Compra", "Nombre Proveedor", "Pagado"};

            ArrayList<Requerimiento_1> lista;

            try{
                lista = controlador.consultaRequerimiento_1(limit);
                Object[][] datos = new Object[lista.size()][4];
                int index = 0;

                for(Requerimiento_1 i: lista){
                    datos[index][0] = i.getFechaCompra();
                    datos[index][1] = i.getCodCompra();
                    datos[index][2] = i.getNombreProveedor();
                    datos[index][3] = i.getPagado();
                    index ++;
                }
                DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
                Tabla1.setModel(model);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        if (RbtnReq2.isSelected() & !RBtnFiltro.isSelected()){
            String[] columnNombre = {"Fec Inicio", "Nombre Constructora", "Nombre Ciudad", "Nombre Lider", "Cod. Tipo", "Estrato"};

            ArrayList<Requerimiento_2> lista;

            try{
                lista = controlador.consultaRequerimiento_2(limit);
                Object[][] datos = new Object[lista.size()][6];
                int index = 0;

                for(Requerimiento_2 i: lista){
                    datos[index][0] = i.getFechaInicio();
                    datos[index][1] = i.getConstructora();
                    datos[index][2] = i.getCiudad();
                    datos[index][3] = i.getLider();
                    datos[index][4] = i.getTipo();
                    datos[index][5] = i.getEstrato();
                    index ++;
                }
                DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
                Tabla1.setModel(model);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        
        if (RbtnReq2.isSelected() & RBtnFiltro.isSelected()){
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateIni = sdf.format(DateIni.getDate());
            String dateFin = sdf.format(DateFin.getDate());
            String ciudad = campoCiudad.getText();
                             
            if(ciudad.equals("")){
                ciudad = null;
            }

            String[] columnNombre = {"Fec Inicio", "Nombre Constructora", "Nombre Ciudad", "Nombre Lider", "Cod. Tipo", "Estrato"};

            ArrayList<Requerimiento_2> lista;

            try{
                lista = controlador.consultaRequerimiento_2(dateIni, dateFin, ciudad, limit);
                Object[][] datos = new Object[lista.size()][6];
                int index = 0;

                for(Requerimiento_2 i: lista){
                    datos[index][0] = i.getFechaInicio();
                    datos[index][1] = i.getConstructora();
                    datos[index][2] = i.getCiudad();
                    datos[index][3] = i.getLider();
                    datos[index][4] = i.getTipo();
                    datos[index][5] = i.getEstrato();
                    index ++;
                }
                DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
                Tabla1.setModel(model);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        
        
        
        if (RbtnReq3.isSelected()){
            String[] columnNombre = {"Abrev"};

            ArrayList<Requerimiento_3> lista;

            try{
                lista = controlador.consultaRequerimiento_3(limit);
                Object[][] datos = new Object[lista.size()][1];
                int index = 0;

                for(Requerimiento_3 i: lista){
                    datos[index][0] = i.getAbrev();
                    index ++;
                }
                DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
                Tabla1.setModel(model);
            }catch(SQLException e){
                System.out.println(e);
            }
        }


    }//GEN-LAST:event_BtnConsultaActionPerformed

    private void RbtnReq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnReq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnReq3ActionPerformed

    private void RbtnReq3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RbtnReq3StateChanged
        // TODO add your handling code here:
        if (RbtnReq3.isSelected()){
            RbtnReq1.setSelected(false);
            RbtnReq2.setSelected(false);
        }
    }//GEN-LAST:event_RbtnReq3StateChanged

    private void RbtnReq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnReq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnReq2ActionPerformed

    private void RbtnReq2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RbtnReq2StateChanged
        // TODO add your handling code here:
        if (RbtnReq2.isSelected()){
            RbtnReq1.setSelected(false);
            RbtnReq3.setSelected(false);
        }
    }//GEN-LAST:event_RbtnReq2StateChanged

    private void RbtnReq1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RbtnReq1StateChanged
        // TODO add your handling code here:
        if (RbtnReq1.isSelected()){
            RbtnReq2.setSelected(false);
            RbtnReq3.setSelected(false);
        }
    }//GEN-LAST:event_RbtnReq1StateChanged

    private void RBtnFiltroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RBtnFiltroStateChanged
        // TODO add your handling code here:
         if (RBtnFiltro.isSelected()){
            campoCiudad.setEnabled(true);
            DateIni.setEnabled(true);
            DateFin.setEnabled(true);

            labelCiudad.setForeground(Color.BLACK);
            labelDateIni.setForeground(Color.BLACK);
            labelDateFin.setForeground(Color.BLACK);
            
            RbtnReq1.setSelected(false);
            RbtnReq2.setSelected(true);
            RbtnReq3.setSelected(false);
            RbtnReq1.setEnabled(false);
            //RbtnReq2.setEnabled(false);
            RbtnReq3.setEnabled(false);

        }else{
            campoCiudad.setEnabled(false);
            DateIni.setEnabled(false);
            DateFin.setEnabled(false);
            
            labelCiudad.setForeground(Color.GRAY);
            labelDateIni.setForeground(Color.GRAY);
            labelDateFin.setForeground(Color.GRAY);
            
            RbtnReq1.setEnabled(true);
            RbtnReq2.setEnabled(true);
            RbtnReq3.setEnabled(true);
            
         }
    }//GEN-LAST:event_RBtnFiltroStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRequerimientos().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsulta;
    private com.toedter.calendar.JDateChooser DateFin;
    private com.toedter.calendar.JDateChooser DateIni;
    private javax.swing.JTabbedPane PanelPestanas;
    private javax.swing.JRadioButton RBtnFiltro;
    private javax.swing.JRadioButton RbtnReq1;
    private javax.swing.JRadioButton RbtnReq2;
    private javax.swing.JRadioButton RbtnReq3;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDateFin;
    private javax.swing.JLabel labelDateIni;
    private javax.swing.JTextField numReg;
    // End of variables declaration//GEN-END:variables
}
